#! /usr/bin/python3

import os
import sys
from time import sleep

def scrollOn():
    os.system("synclient VertTwoFingerScroll=1")

def scrollOff():
    os.system("synclient VertTwoFingerScroll=0")

if len(sys.argv) == 1:
    print("Usage: scroll [arg1] [arg2] ...")
    sys.exit()

args = sys.argv[1:]
scroll = False
delay = 1
cmd = "xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME"

scrollOff()

while True:
    active_window = os.popen(cmd).read().lower()
    found_arg = False
    for arg in args:
        if arg in active_window:
            found_arg = True
            if not scroll:
                scrollOn()
                scroll = True
            break
    if scroll and not found_arg:
        scrollOff()
        scroll = False
    sleep(delay)
