#! /usr/bin/python3

import os
import sys
from time import sleep

def scroll_on():
    os.system("synclient VertTwoFingerScroll=1")

def scroll_off():
    os.system("synclient VertTwoFingerScroll=0")

if len(sys.argv) == 1:
    print("Usage: scroll <string1> [<string2> <string3>...]")
    sys.exit()

args = sys.argv[1:]
args = [arg.lower() for arg in args]
scroll_enabled = False
delay = 1
cmd = "xprop -id $(xprop -root 32x '\t$0' _NET_ACTIVE_WINDOW | cut -f 2) _NET_WM_NAME"

scroll_off()

while True:
    cmd_output = os.popen(cmd).read().lower().split('"')
    if len(cmd_output) > 1:
        active_window_name = cmd_output[1]
    else:
        active_window_name = ""
    found_arg = False
    for arg in args:
        if arg in active_window_name:
            found_arg = True
            if not scroll_enabled:
                scroll_on()
                scroll_enabled = True
            break
    if scroll_enabled and not found_arg:
        scroll_off()
        scroll_enabled = False
    sleep(delay)
